### ISSUE TITLE
Latest update has broken SESE

### ISSUE THREAD

**Issue by Ragonz2** [rexxar-tc/SEServerExtender#10]
When trying to load the latest version of SE with SESE the error shown below shows up. This has been tested on multiple servers.

2016-01-08 04:37:24.778 - Thread:   5 ->     ERROR: Exception during objectbuilder read! (xml): MyObjectBuilder_Checkpoint

2016-01-08 04:37:24.778 - Thread:   5 ->     Exception occured: System.InvalidOperationException: There is an error in XML document (41, 53). ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.

   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)

   at VRage.ObjectBuilders.SerializableDefinitionId.set_TypeIdString(String value)

   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read66_SerializableDefinitionId(Boolean checkType)

   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read689_Item(Boolean isNullable, Boolean checkType)

   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read171_MyObjectBuilder_ToolbarItem(Boolean isNullable, Boolean checkType)

   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read272_Slot(Boolean checkType)

   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read273_MyObjectBuilder_Toolbar(Boolean isNullable, Boolean checkType)

   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read629_MyObjectBuilder_Checkpoint(Boolean isNullable, Boolean checkType)

   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read1232_MyObjectBuilder_Checkpoint()

   --- End of inner exception stack trace ---

   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)

   at VRage.ObjectBuilders.MyObjectBuilderSerializer.DeserializeXML(Stream reader, MyObjectBuilder_Base& objectBuilder, Type builderType)

2016-01-08 04:37:24.778 - Thread:   5 ->     InnerException: 

2016-01-08 04:37:24.778 - Thread:   5 ->     Exception occured: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.

   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)

   at VRage.ObjectBuilders.SerializableDefinitionId.set_TypeIdString(String value)

   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read66_SerializableDefinitionId(Boolean checkType)

   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read689_Item(Boolean isNullable, Boolean checkType)

   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read171_MyObjectBuilder_ToolbarItem(Boolean isNullable, Boolean checkType)

   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read272_Slot(Boolean checkType)

   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read273_MyObjectBuilder_Toolbar(Boolean isNullable, Boolean checkType)

   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read629_MyObjectBuilder_Checkpoint(Boolean isNullable, Boolean checkType)

   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read1232_MyObjectBuilder_Checkpoint()

2016-01-08 04:37:24.778 - Thread:   5 ->     Failed to deserialize file 'C:\Pingperfect\Users\username\6384\Saves\Pingperfect\Sandbox.sbc'

2016-01-08 04:37:24.779 - Thread:   5 ->     This world can not be loaded. It has been created in newer version of the game.

**Comment by tbankstemp** [comment]
I can confirm this. It's happening with both of my servers as well.
Thank you.

**Comment by RhythmNz** [comment]
I can confirm this. It's happening with both of my servers as well.
Thank you.

**Comment by SilentSymphony** [comment]
Extender is in bad shape guys, rexxar is trying but with what keen has done it is a pretty big deal, even the author of SEToolbox has decided to back out of supporting SE..

Don't lose hope just yet but do understand this is no small problem and as such if a solution does come it may take some time.

**Comment by rexxar-tc** [comment]
Don't expect a fix any time soon; I've given up on SESE. I don't know what Keen did, but it's big and beyond my experience and ability to fix. I've asked Tyrsis for help, and Dodexahedron was planning on starting SESE work again (he's on vacation til next week, I think), so the project probably isn't dead.

I'm super pissed off and discouraged by how Keen has been handling the community lately. If they don't get their collective head out of their ass soon, I'm just gonna quit SE altogether. I have better things to do with my time than work on a game when the developers show utter disregard for their community.

I mean, Keen are well within their rights to make the sort of huge changes that happened here, but they should know how important SESE is to people (over 200 people use this branch, including some hosts like Pingperfect). I really would have appreciated a warning that everything would be broken.
