### ISSUE TITLE
issue with grid scanning.

### ISSUE THREAD

**Issue by Wrsaith** [rexxar-tc/SEServerExtender#16]
these grid scans are being run by our auto clean up script every time it tries to run. This is alwos 
2016-02-08 04:56:35.0517|Info|getting grids
2016-02-08 04:56:35.0517|Info|got grids
2016-02-08 04:56:35.3787|Warn|Handler Problems: 1000 - System.InvalidOperationEx
ception: Nullable object must have a value.
   at EssentialsPlugin.Utility.CubeGrids.GetGridsUnconnected(HashSet`1 connected
List, HashSet`1 entitiesToConfirm)
   at EssentialsPlugin.Utility.CubeGrids.ScanGrids(UInt64 userId, String[] words
)
   at EssentialsPlugin.ProcessHandlers.ProcessCleanup.ProcessTriggerItem(Setting
sCleanupTriggerItem item)
   at EssentialsPlugin.ProcessHandlers.ProcessCleanup.Handle()
   at EssentialsPlugin.Essentials.<>c__DisplayClass225_0.<PluginProcessing>b__0(
)
2016-02-08 04:56:35.3787|Error|:GetGridsUnconnected(0,0)
2016-02-08 04:56:35.3787|Error|:ScanGrids(0,0)
2016-02-08 04:56:35.3787|Error|:ProcessTriggerItem(0,0)
2016-02-08 04:56:35.3787|Error|:Handle(0,0)
2016-02-08 04:56:35.3897|Error|:<PluginProcessing>b__0(0,0)
2016-02-08 04:56:36.3908|Info|getting grids
2016-02-08 04:56:36.4048|Info|got grids
sending: 246, Default_Astronaut

434|Error|Entity list busy, skipping scan.
    |System.InvalidOperationException: Collection was modified; enumeration oper
ation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at Sandbox.ModAPI.MyEntitiesHelper_ModAPI.Sandbox.ModAPI.IMyEntities.GetEntit
ies(HashSet`1 entities, Func`2 collect)
   at EssentialsPlugin.ProcessHandlers.ProcessBlockEnforcement.ScanForBlockItems
()

2016-02-08 05:01:35.9299|Warn|Handler Problems: 1000 - System.InvalidOperationEx
ception: Nullable object must have a value.
   at EssentialsPlugin.Utility.CubeGrids.GetGridsUnconnected(HashSet`1 connected
List, HashSet`1 entitiesToConfirm)
   at EssentialsPlugin.Utility.CubeGrids.ScanGrids(UInt64 userId, String[] words
)
   at EssentialsPlugin.ProcessHandlers.ProcessCleanup.ProcessTriggerItem(Setting
sCleanupTriggerItem item)
   at EssentialsPlugin.ProcessHandlers.ProcessCleanup.Handle()
   at EssentialsPlugin.Essentials.<>c__DisplayClass225_0.<PluginProcessing>b__0(
)
2016-02-08 05:01:35.9299|Error|:GetGridsUnconnected(0,0)
2016-02-08 05:01:35.9299|Error|:ScanGrids(0,0)
2016-02-08 05:01:35.9299|Error|:ProcessTriggerItem(0,0)
2016-02-08 05:01:35.9299|Error|:Handle(0,0)
2016-02-08 05:01:35.9299|Error|:<PluginProcessing>b__0(0,0)
2016-02-08 05:01:36.9400|Info|getting grids
2016-02-08 05:01:36.9400|Info|got grids

2016-02-08 05:04:16.9351|Info|Asynchronous Save Setup Started: 242.0138ms
2016-02-08 05:04:19.1582|Info|Asynchronous Save Completed: 2465.141ms
2016-02-08 05:06:36.2011|Info|getting grids
2016-02-08 05:06:36.2011|Info|got grids
2016-02-08 05:06:36.4851|Warn|Handler Problems: 1000 - System.InvalidOperationEx
ception: Nullable object must have a value.
   at EssentialsPlugin.Utility.CubeGrids.GetGridsUnconnected(HashSet`1 connected
List, HashSet`1 entitiesToConfirm)
   at EssentialsPlugin.Utility.CubeGrids.ScanGrids(UInt64 userId, String[] words
)
   at EssentialsPlugin.ProcessHandlers.ProcessCleanup.ProcessTriggerItem(Setting
sCleanupTriggerItem item)
   at EssentialsPlugin.ProcessHandlers.ProcessCleanup.Handle()
   at EssentialsPlugin.Essentials.<>c__DisplayClass225_0.<PluginProcessing>b__0(
)
2016-02-08 05:06:36.4851|Error|:GetGridsUnconnected(0,0)
2016-02-08 05:06:36.4851|Error|:ScanGrids(0,0)
2016-02-08 05:06:36.4931|Error|:ProcessTriggerItem(0,0)
2016-02-08 05:06:36.4931|Error|:Handle(0,0)
2016-02-08 05:06:36.4931|Error|:<PluginProcessing>b__0(0,0)
2016-02-08 05:06:37.4952|Info|getting grids
2016-02-08 05:06:37.5082|Info|got grids

2016-02-08 05:11:36.7713|Info|getting grids
2016-02-08 05:11:36.7813|Info|got grids
2016-02-08 05:11:37.0623|Warn|Handler Problems: 1000 - System.InvalidOperationEx
ception: Nullable object must have a value.
   at EssentialsPlugin.Utility.CubeGrids.GetGridsUnconnected(HashSet`1 connected
List, HashSet`1 entitiesToConfirm)
   at EssentialsPlugin.Utility.CubeGrids.ScanGrids(UInt64 userId, String[] words
)
   at EssentialsPlugin.ProcessHandlers.ProcessCleanup.ProcessTriggerItem(Setting
sCleanupTriggerItem item)
   at EssentialsPlugin.ProcessHandlers.ProcessCleanup.Handle()
   at EssentialsPlugin.Essentials.<>c__DisplayClass225_0.<PluginProcessing>b__0(
)
2016-02-08 05:11:37.0623|Error|:GetGridsUnconnected(0,0)
2016-02-08 05:11:37.0623|Error|:ScanGrids(0,0)
2016-02-08 05:11:37.0623|Error|:ProcessTriggerItem(0,0)
2016-02-08 05:11:37.0623|Error|:Handle(0,0)
2016-02-08 05:11:37.0623|Error|:<PluginProcessing>b__0(0,0)
2016-02-08 05:11:38.0734|Info|getting grids
2016-02-08 05:11:38.0874|Info|got grids
2016-02-08 05:14:17.3065|Info|Asynchronous Save Setup Started: 602.0344ms
2016-02-08 05:14:19.5936|Info|Asynchronous Save Completed: 2889.1652ms
2016-02-08 05:16:37.3405|Info|getting grids
2016-02-08 05:16:37.3575|Info|got grids
2016-02-08 05:16:37.6455|Warn|Handler Problems: 1000 - System.InvalidOperationEx
ception: Nullable object must have a value.
   at EssentialsPlugin.Utility.CubeGrids.GetGridsUnconnected(HashSet`1 connected
List, HashSet`1 entitiesToConfirm)
   at EssentialsPlugin.Utility.CubeGrids.ScanGrids(UInt64 userId, String[] words
)
   at EssentialsPlugin.ProcessHandlers.ProcessCleanup.ProcessTriggerItem(Setting
sCleanupTriggerItem item)
   at EssentialsPlugin.ProcessHandlers.ProcessCleanup.Handle()
   at EssentialsPlugin.Essentials.<>c__DisplayClass225_0.<PluginProcessing>b__0(
)
2016-02-08 05:16:37.7595|Error|:GetGridsUnconnected(0,0)
2016-02-08 05:16:37.7705|Error|:ScanGrids(0,0)
2016-02-08 05:16:37.7835|Error|:ProcessTriggerItem(0,0)
2016-02-08 05:16:37.7835|Error|:Handle(0,0)
2016-02-08 05:16:37.8055|Error|:<PluginProcessing>b__0(0,0)
2016-02-08 05:16:38.8166|Info|getting grids
2016-02-08 05:16:38.8306|Info|got grids

---

This is what it says when an admin runs the scan grid.

2016-02-08 05:22:25.2614|Info|Chat - Client 'Wrsaith[]': /admin scan grids nopow
er
2016-02-08 05:22:25.3224|Info|Chat - Server: Scanning for ships with options: Ha
s Power=false
2016-02-08 05:22:25.3444|Info|getting grids
2016-02-08 05:22:25.3664|Info|got grids
2016-02-08 05:22:25.6974|Info|scan grid
    |System.InvalidOperationException: Nullable object must have a value.
   at EssentialsPlugin.Utility.CubeGrids.GetGridsUnconnected(HashSet`1 connected
List, HashSet`1 entitiesToConfirm)
   at EssentialsPlugin.Utility.CubeGrids.ScanGrids(UInt64 userId, String[] words
)
   at EssentialsPlugin.ChatHandlers.AdminScan.HandleAdminScanGrids.HandleCommand
(UInt64 userId, String[] words)

**Comment by rexxar-tc** [comment]
I can't seem to reproduce this, not sure what's going on
