### ISSUE TITLE
SESE Crashes on start up when loading and instance 

### ISSUE THREAD

**Issue by markam67** [rexxar-tc/SEServerExtender#18]
SESE crashes with below error message

2016-02-25 13:41:53.8663|Info|Starting SEServerExtender with 3 arguments: instance=New Private Survival 2016
        autosave=10
        instancepath=C:\ProgramData\SpaceEngineersDedicated\New Private Survival 2016
2016-02-25 13:41:53.9023|Info|Finished creating server!
2016-02-25 13:41:53.9108|Info|Finished loading DedicatedServerAssemblyWrapper
2016-02-25 13:41:53.9108|Info|Finished loading PluginManager
2016-02-25 13:41:53.9108|Info|Finished loading FactionsManager
2016-02-25 13:41:53.9273|Info|Finished loading EntityEventManager
2016-02-25 13:41:53.9403|Info|Finished loading ChatManager
2016-02-25 13:41:53.9403|Info|Common instance pre-selected: 'New Private Survival 2016'
2016-02-25 13:41:53.9403|Info|WCF disabled
2016-02-25 13:41:53.9403|Info|Autosave interval: 10
2016-02-25 13:41:53.9403|Info|Full path pre-selected: 'C:\ProgramData\SpaceEngineersDedicated\New Private Survival 2016'
2016-02-25 13:41:53.9588|Info|end parsing
2016-02-25 13:41:53.9588|Error|AppDomain.UnhandledException - System.TypeLoadException: Could not load type 'Sandbox.Definitions.MyDefinitionId' from assembly 'VRage.Game, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at SEServerExtender.Program.StartGui()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Unhandled Exception: System.TypeLoadException: Could not load type 'Sandbox.Definitions.MyDefinitionId' from assembly 'VRage.Game, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at SEServerExtender.Program.StartGui()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by rexxar-tc** [comment]
I just published a new release that fixes this

**Comment by markam67** [comment]
Thank you,
Did not see it.
Markam67 

Date: Thu, 25 Feb 2016 10:58:08 -0800
