### ISSUE TITLE
Server crashes when running in headless mode

### ISSUE THREAD

**Issue by Ragonz2** [rexxar-tc/SEServerExtender#3]
When running the server through a service manager such as FireDeamon it runs the server as a service. This crashes everytime. However the exact same commandline launched from a batch file works fine.

Commandline
SEServerExtender.exe nogui noconsole  autostart gamepath=C:\5612\ instance=C:\5612\

Log File

2015-11-30 16:22:39.8440|Info|SEServerExtender.Program.Start|Starting SEServerExtender with 5 arguments: nogui
    noconsole
    autostart
    gamepath=C:\5612\
    instance=C:\5612\
2015-11-30 16:22:59.4005|Info|SEServerExtender.Program.Start|Starting SEServerExtender with 3 arguments: -report
    C:\5612\SpaceEngineersDedicated.log
    Space Engineers
2015-11-30 16:22:59.4866|Info|SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper..ctor|Finished loading SandboxGameAssemblyWrapper
2015-11-30 16:22:59.4936|Error|SEModAPIInternal.API.Server.ServerNetworkManager.ReflectionUnitTest|System.TypeLoadException: Could not find internal type for AttachToCockpitMsg
   at SEModAPIInternal.API.Server.ServerNetworkManager.ReflectionUnitTest()
    |System.TypeLoadException: Could not find internal type for AttachToCockpitMsg
   at SEModAPIInternal.API.Server.ServerNetworkManager.ReflectionUnitTest()
2015-11-30 16:22:59.4936|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunBaseReflectionUnitTests|ServerNetworkManager reflection validation failed!
2015-11-30 16:22:59.5426|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to find method 'SendRemovedBlocks' in type 'Sandbox.Game.Multiplayer.MySyncGrid'
2015-11-30 16:22:59.5426|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to find method 'BuildBlocksSuccess' in type 'Sandbox.Game.Multiplayer.MySyncGrid'
2015-11-30 16:22:59.5426|Error|SEModAPI.API.Utility.Reflection.HasField|Failed to find field 'm_destroyBlockQueue' in type 'Sandbox.Game.Multiplayer.MySyncGrid'
2015-11-30 16:22:59.5426|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunEntityReflectionUnitTests|CubeGridNetworkManager reflection validation failed!
2015-11-30 16:22:59.5426|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGridThrusterManager.ReflectionUnitTest|System.Exception: Could not find type for CubeGridThrusterManager
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGridThrusterManager.ReflectionUnitTest()
    |System.Exception: Could not find type for CubeGridThrusterManager
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGridThrusterManager.ReflectionUnitTest()
2015-11-30 16:22:59.5426|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunEntityReflectionUnitTests|CubeGridThrusterManager reflection validation failed!
2015-11-30 16:22:59.5426|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to find method 'set_RemainingCapacity' in type 'Sandbox.Game.GameSystems.Electricity.MyBattery'
2015-11-30 16:22:59.5546|Error|SEModAPI.API.Utility.Reflection.HasField|Failed to find field 'm_remainingCapacity' in type 'Sandbox.Game.GameSystems.Electricity.MyBattery'
2015-11-30 16:22:59.5546|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunEntityReflectionUnitTests|CharacterEntity reflection validation failed!
2015-11-30 16:22:59.5807|Error|SEModAPI.API.Utility.Reflection.HasField|Failed to find field 'm_batteryBlockDefinition' in type 'Sandbox.Game.Entities.MyBatteryBlock'
2015-11-30 16:22:59.5807|Error|SEModAPI.API.Utility.Reflection.HasField|Failed to find field 'SyncObject' in type 'Sandbox.Game.Entities.MyBatteryBlock'
2015-11-30 16:22:59.5807|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|BatteryBlockEntity reflection validation failed!
2015-11-30 16:22:59.5807|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.BatteryBlockNetworkManager.ReflectionUnitTest|System.Exception: Could not find internal type for BatteryBlockNetworkManager
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.BatteryBlockNetworkManager.ReflectionUnitTest()
    |System.Exception: Could not find internal type for BatteryBlockNetworkManager
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.BatteryBlockNetworkManager.ReflectionUnitTest()
2015-11-30 16:22:59.5807|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|BatteryBlockNetworkManager reflection validation failed!
2015-11-30 16:22:59.5917|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to find method 'SetThrustOverride' in type 'Sandbox.Game.Entities.MyThrust'
2015-11-30 16:22:59.5917|Error|SEModAPI.API.Utility.Reflection.HasField|Failed to find field 'SyncObject' in type 'Sandbox.Game.Entities.MyThrust'
2015-11-30 16:22:59.5917|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|ThrustEntity reflection validation failed!
2015-11-30 16:22:59.5917|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.ThrustNetworkManager.ReflectionUnitTest|System.Exception: Could not find network manager type for ThrustEntity
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.ThrustNetworkManager.ReflectionUnitTest()
    |System.Exception: Could not find network manager type for ThrustEntity
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.ThrustNetworkManager.ReflectionUnitTest()
2015-11-30 16:22:59.5917|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|ThrustNetworkManager reflection validation failed!
2015-11-30 16:22:59.6037|Error|SEModAPI.API.Utility.Reflection.HasField|Failed to find field 'm_ammoInventory' in type 'Sandbox.Game.Weapons.MyLargeTurretBase'
2015-11-30 16:22:59.6037|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|TurretBaseEntity reflection validation failed!
2015-11-30 16:22:59.6037|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to find method 'set_MaxPowerOutput' in type 'Sandbox.Game.Entities.MyReactor'
2015-11-30 16:22:59.6037|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|ReactorEntity reflection validation failed!
2015-11-30 16:22:59.6037|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to find method 'set_MaxPowerOutput' in type 'Sandbox.Game.Entities.Blocks.MySolarPanel'
2015-11-30 16:22:59.6037|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|SolarPanelEntity reflection validation failed!
2015-11-30 16:22:59.6037|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to find method 'get_Velocity' in type 'Sandbox.Game.Entities.Blocks.MyPistonBase'
2015-11-30 16:22:59.6037|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to find method 'set_Velocity' in type 'Sandbox.Game.Entities.Blocks.MyPistonBase'
2015-11-30 16:22:59.6167|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to find method 'get_MinLimit' in type 'Sandbox.Game.Entities.Blocks.MyPistonBase'
2015-11-30 16:22:59.6167|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to find method 'set_MinLimit' in type 'Sandbox.Game.Entities.Blocks.MyPistonBase'
2015-11-30 16:22:59.6167|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to find method 'get_MaxLimit' in type 'Sandbox.Game.Entities.Blocks.MyPistonBase'
2015-11-30 16:22:59.6167|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to find method 'set_MaxLimit' in type 'Sandbox.Game.Entities.Blocks.MyPistonBase'
2015-11-30 16:22:59.6167|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|PistonEntity reflection validation failed!
2015-11-30 16:22:59.6167|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.PistonNetworkManager.ReflectionUnitTest|System.Exception: Could not find internal type for PistonNetworkManager
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.PistonNetworkManager.ReflectionUnitTest()
    |System.Exception: Could not find internal type for PistonNetworkManager
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.PistonNetworkManager.ReflectionUnitTest()
2015-11-30 16:22:59.6167|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|PistonNetworkManager reflection validation failed!
2015-11-30 16:22:59.6167|Info|SEModAPIExtensions.API.Server..ctor|Finished creating server!
2015-11-30 16:22:59.6357|Info|SEModAPIInternal.API.Server.DedicatedServerAssemblyWrapper.get_Instance|Finished loading DedicatedServerAssemblyWrapper
2015-11-30 16:22:59.6357|Info|SEModAPIExtensions.API.PluginManager..ctor|Finished loading PluginManager
2015-11-30 16:22:59.6357|Info|SEModAPIInternal.API.Common.FactionsManager.get_Instance|Finished loading FactionsManager
2015-11-30 16:22:59.6357|Info|SEModAPIInternal.API.Common.EntityEventManager.get_Instance|Finished loading EntityEventManager
2015-11-30 16:22:59.6627|Info|SEModAPIExtensions.API.ChatManager..ctor|Finished loading ChatManager
2015-11-30 16:22:59.6647|Info|SEModAPIExtensions.API.Server.ProcessCommandLineArgs|end parsing
2015-11-30 16:22:59.6647|Info|SEServerExtender.Program.Start|Opening up WCF service listener at http://localhost:8500/ServerService/
2015-11-30 16:22:59.7038|Info|SEServerExtender.Program.Start|Exception - System.ServiceModel.AddressAccessDeniedException: HTTP could not register URL http://+:8500/ServerService/. Your process does not have access rights to this namespace (see http://go.microsoft.com/fwlink/?LinkId=70353 for details). ---> System.Net.HttpListenerException: Access is denied
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at System.ServiceModel.Channels.SharedHttpTransportManager.OnOpen()
   --- End of inner exception stack trace ---
   at System.ServiceModel.Channels.SharedHttpTransportManager.OnOpen()
   at System.ServiceModel.Channels.TransportManager.Open(TransportChannelListener channelListener)
   at System.ServiceModel.Channels.TransportManagerContainer.Open(SelectTransportManagersCallback selectTransportManagerCallback)
   at System.ServiceModel.Channels.HttpChannelListener`1.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.DatagramChannelDemuxer`2.OnOuterListenerOpen(ChannelDemuxerFilter filter, IChannelListener listener, TimeSpan timeout)
   at System.ServiceModel.Channels.SingletonChannelListener`3.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Dispatcher.ChannelDispatcher.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.ServiceHostBase.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Security.NegotiationTokenAuthenticator`1.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Security.SymmetricSecurityProtocolFactory.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Security.SecurityListenerSettingsLifetimeManager.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.SecurityChannelListener`1.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Dispatcher.ChannelDispatcher.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.ServiceHostBase.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Security.SecuritySessionSecurityTokenAuthenticator.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Security.SecurityUtils.OpenTokenAuthenticatorIfRequired(SecurityTokenAuthenticator tokenAuthenticator, TimeSpan timeout)
   at System.ServiceModel.Security.SecuritySessionServerSettings.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Security.SecurityListenerSettingsLifetimeManager.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.SecurityChannelListener`1.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Dispatcher.ChannelDispatcher.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.ServiceHostBase.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at SEServerExtender.Program.Start(String[] args)
    |System.ServiceModel.AddressAccessDeniedException: HTTP could not register URL http://+:8500/ServerService/. Your process does not have access rights to this namespace (see http://go.microsoft.com/fwlink/?LinkId=70353 for details). ---> System.Net.HttpListenerException: Access is denied
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at System.ServiceModel.Channels.SharedHttpTransportManager.OnOpen()
   --- End of inner exception stack trace ---
   at System.ServiceModel.Channels.SharedHttpTransportManager.OnOpen()
   at System.ServiceModel.Channels.TransportManager.Open(TransportChannelListener channelListener)
   at System.ServiceModel.Channels.TransportManagerContainer.Open(SelectTransportManagersCallback selectTransportManagerCallback)
   at System.ServiceModel.Channels.HttpChannelListener`1.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.DatagramChannelDemuxer`2.OnOuterListenerOpen(ChannelDemuxerFilter filter, IChannelListener listener, TimeSpan timeout)
   at System.ServiceModel.Channels.SingletonChannelListener`3.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Dispatcher.ChannelDispatcher.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.ServiceHostBase.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Security.NegotiationTokenAuthenticator`1.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Security.SymmetricSecurityProtocolFactory.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Security.SecurityListenerSettingsLifetimeManager.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.SecurityChannelListener`1.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Dispatcher.ChannelDispatcher.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.ServiceHostBase.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Security.SecuritySessionSecurityTokenAuthenticator.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Security.SecurityUtils.OpenTokenAuthenticatorIfRequired(SecurityTokenAuthenticator tokenAuthenticator, TimeSpan timeout)
   at System.ServiceModel.Security.SecuritySessionServerSettings.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Security.SecurityListenerSettingsLifetimeManager.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.SecurityChannelListener`1.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Dispatcher.ChannelDispatcher.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.ServiceHostBase.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at SEServerExtender.Program.Start(String[] args)
Access is denied System.Net.HttpListenerException Void AddAllPrefixes()    at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at System.ServiceModel.Channels.SharedHttpTransportManager.OnOpen()
2015-11-30 16:23:00.9891|Info|SEServerExtender.Program.Start|Starting SEServerExtender with 5 arguments: nogui
    noconsole
    autostart
    gamepath=C:\5612\
    instance=C:\5612\

**Comment by rexxar-tc** [comment]
Is this new behavior with my build, or did the 1.101.x builds also show this behavior?

SESE has an internal WCF/web server; it's meant for remote management. It sounds like your service manager is stopping SESE from initializing the server, which causes the crash. I haven't looked at that part of the code in depth, so I'm not sure why it would cause the crash. I think SESE actually uses a subset of the WCF server to interact with the vanilla SE server process.

**Comment by Ragonz2** [comment]
New behaviour old sese didn't do this

**Comment by rexxar-tc** [comment]
I really have no idea, I didn't touch that section of code. I think that dodexahedron's builds were signed or something, and mine aren't so your service manager is locking it out for security reasons. It would probably work if you used the exe from previous builds and just replaced the dlls from mine; I don't think anything has changed in the main executable, just the dll files. Other than that, I don't know what to tell you other than check security settings in your service manger.

**Comment by rexxar-tc** [comment]
I've had a couple similar reports, so I did some digging. Try this build that has WCF disabled by default. https://github.com/rexxar-tc/SEServerExtender/releases/tag/SEServerExtender-v1.111.13.29-noWCF

(or you could pull the noWCF branch I just created)

**Comment by Ragonz2** [comment]
Now works fine. Thank you

**Comment by rexxar-tc** [comment]
Good to hear. I'll keep up noWCF builds then.
